name: watt
description: Flutter prebuilt widgets and utils to make development faster
version: 1.3.0
repository: https://github.com/weaze-id/watt

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^5.1.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.18.0
  witt: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
