name: watt
description: Flutter prebuilt widgets and utils to make development faster
version: 1.10.0
repository: https://github.com/weaze-id/watt

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
