name: watt
description: Flutter prebuilt widgets and utils to make development faster
version: 3.0.0
repository: https://github.com/weaze-id/watt

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
