name: watt
description: Flutter prebuilt widgets and utils to make development faster
version: 2.2.2
repository: https://github.com/weaze-id/watt

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
